// Components
import React from 'react';
import Head from 'next/head'
import { useRouter } from 'next/router';
import { Card, CardHeader, CardBody, CardFooter } from '@nextui-org/react';
import Image from 'next/image';

// Data
import { GameListData } from '@/data/game';

// Contents

export default function ProductsPage() {
    const router = useRouter();
    const { gamelist } = router.query;
    const game = GameListData.find((item) => item.title === gamelist);
    return (
        <div>
            <Head>
                <title>{}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto max-w-7xl sm:px-6 sm: py-32 lg:px-8 text-center p-5">
                {game ? (
                    <div>
                        <h4 className="text-center text-3xl sm:text-2xl md:text-lg lg:text-xl xl:text-2xl 2xl:text-3xl mt-1">{game.title}</h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 p-5">
                                <div className="p-3 mt-2">
                                    <Image src={game.img} alt="profile" className={game.title} width="100%" height="auto" />
                                </div>
                                <div className="p-3 mt-15">
                                    <h1 className="text-3xl sm:text-2xl mt-1">{game.contents}</h1>
                                    <p>{game.under}</p>
                                </div>
                            </div>
                    </div>
                ) : (
                    <h4 className="text-3xl sm:text-2xl mt-1">ไม่พบข้อมูลสินค้า</h4>
                )}
            </div>
        </div>
    )
}
