import { GameListData } from "@/data/game";
import { Card, CardBody, CardFooter, CardHeader } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";

export default function ProductsPage() {
	const router = useRouter();
	const { gamelist } = router.query;
	const game = GameListData.find((item) => item.title === gamelist);
	return (
		<div>
			<Head>
				<title>{}</title>
				<meta content="Generated by create next app" name="description" />
				<meta content="width=device-width, initial-scale=1" name="viewport" />
				<link href="/logo.ico" rel="icon" />
			</Head>
			<div className="sm: mx-auto max-w-7xl p-5 py-32 text-center sm:px-6 lg:px-8">
				{game ? (
					<div>
						<h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
							{game.title}
						</h2>
						<div className="grid grid-cols-1 p-5 md:grid-cols-2">
							<div className="mt-2 p-3">
								<Image
									alt="profile"
									className={game.title}
									height="auto"
									src={game.img}
									width="100%"
								/>
							</div>
							<div className="mt-15 p-3">
								<h1 className="mt-1 text-3xl sm:text-2xl">{game.contents}</h1>
								<p>{game.under}</p>
							</div>
						</div>
					</div>
				) : (
					<h4 className="mt-1 text-3xl sm:text-2xl">ไม่พบข้อมูลสินค้า</h4>
				)}
			</div>
		</div>
	);
}
