// Components
import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Card, CardHeader, CardBody, CardFooter } from '@nextui-org/react';
import Image from 'next/image';

// Data
import { TeamData } from '@/data/team';

export default function TeamPage() {
  const router = useRouter();
  const { teamlist } = router.query;
  const team = TeamData.find((item) => item.title === teamlist);

  return (
    <div>
      <Head>
        <title>{team ? `${team.title} - CMRU E-Sport` : 'CMRU E-Sport'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <div className="mx-auto max-w-7xl sm:px-6 sm:py-32 lg:px-8 text-center p-5">
        {team ? (
          <div>
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl mt-5">{team.title}</h1>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
              <div>
                <Image src={team.img} alt={team.title} className="rounded-lg" width={200} height={200} />
              </div>
              <div className="text-left">
                <h2 className="text-2xl font-bold mt-2">Team Details</h2>
                <p className="mt-3">{team.contents}</p>
                <p className="mt-3">{team.under}</p>
                <h2 className="text-2xl font-bold mt-8">Team Members</h2>
                <ul className="list-disc pl-5 mt-3">
                  {team.members.map((member, index) => (
                    <li key={index}>{member.name}</li>
                  ))}
                </ul>
                <div className="mt-8">
                  <h3 className="text-xl font-bold">Coaching Staff</h3>
                  <p className="mt-2">
                    Head Coach: {team.coachingStaff.headCoach || 'N/A'}
                    <br />
                    Assistant Coaches:{' '}
                    {team.coachingStaff.assistantCoaches ? team.coachingStaff.assistantCoaches.join(', ') : 'N/A'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <h4 className="text-3xl sm:text-2xl mt-1">Team not found</h4>
        )}
      </div>
    </div>
  );
}
