// Components
import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Card, CardBody } from '@nextui-org/react'
import { useRouter } from 'next/router';

// Data
import { GameListData } from '@/data/game'

// Contents
export default function Home() {
    const router = useRouter();

    return (
        <div>
            <Head>
                <title>CMRU E-Sport</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto max-w-7xl sm:px-6 sm:py-32 lg:px-8 text-center p-5">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl mt-3 p-5"> CMRU E-Sport</h2>

                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl mt-3 p-5">เกมที่จัดแข่งขัน</h2>
                <div className="gap-4 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 mt-5">
                    {GameListData.map((item, index) => (
                        <Link key={index} href={`/games/${encodeURIComponent(item.title)}`}>
                            <Card className="group shadow-sm transition-transform transform duration-300 ease-in-out hover:scale-105" isPressable>
                                <CardBody className="overflow-visible p-5 justify-between">
                                    <Image
                                        shadow="sm"
                                        radius="lg"
                                        width="100%"
                                        height="auto"
                                        alt={item.title}
                                        className="w-full object-cover h-[260px]"
                                        src={item.img}
                                    />
                                    <h1 className="text-left font-bold tracking-tight text-sm 2xl:text-md xl:text-lg lg:text-xl md:text-2xl sm:text-3xl mt-1">{item.title}</h1>
                                    <p>{item.contents}</p>
                                </CardBody>
                            </Card>
                        </Link>
                    ))}
                </div>

            </div>
        </div>
    )
}
