// Components
import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Card, CardHeader, CardBody, CardFooter } from '@nextui-org/react';
import Image from 'next/image';
import Link from 'next/link';

// Data
import { StaffData } from '@/data/staff';

export default function StaffPage() {
    const router = useRouter();
    const { stafflist } = router.query;
    const staff = StaffData.find((item) => item.title === stafflist);

    const hasSocialContact = staff && (staff.facebook || staff.instagram);

    return (
        <div>
            <Head>
                <title>{staff ? `${staff.title} - CMRU E-Sport` : 'CMRU E-Sport'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto max-w-3xl sm:px-6 sm:py-32 lg:px-8 text-center p-5">
                {staff ? (
                    <div>
                        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl mt-5">Staff Info</h1>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
                            <div>
                                <Image src={staff.img} alt={staff.title} className="rounded-lg" width={200} height={200} />
                            </div>
                            <div className="text-left">
                                <h2 className="text-2xl font-bold mt-2">Staff Name</h2>
                                <p className="mt-3 text-xl">{staff.title}</p>
                                <h2 className="text-2xl font-bold mt-8">Education</h2>
                                <p className="mt-3 text-xl">Faculty: {staff.faculty}</p>
                                <p className="mt-3 text-xl">Major: {staff.major}</p>
                                {hasSocialContact && (
                                    <>
                                        <h2 className="text-2xl font-bold mt-8">Social Contact</h2>
                                        <div className="mt-3">
                                            {staff.facebook && (
                                                <Link href={staff.facebook} target="_blank">
                                                    <div className="text-blue-500 hover:underline" target="_blank">Facebook</div>
                                                </Link>
                                            )}
                                        </div>
                                        <div className="mt-3">
                                            {staff.instagram && (
                                                <Link href={staff.instagram} target="_blank">
                                                    <div className="text-purple-500 hover:underline" target="_blank">Instagram</div>
                                                </Link>
                                            )}
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>
                    </div>
                ) : (
                    <h4 className="text-3xl sm:text-2xl mt-1">Staff Not Found</h4>
                )}
            </div>
        </div>
    );
}
