import { StaffData } from "@/data/staff";
import { Card, CardBody, CardFooter, CardHeader } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";

export default function StaffPage() {
	const router = useRouter();
	const { stafflist } = router.query;
	const staff = StaffData.find((item) => item.title === stafflist);

	const hasSocialContact = staff && (staff.facebook || staff.instagram);

	return (
		<div>
			<Head>
				<title>
					{staff ? `${staff.title} - CMRU E-Sport` : "CMRU E-Sport"}
				</title>
				<meta content="Generated by create next app" name="description" />
				<meta content="width=device-width, initial-scale=1" name="viewport" />
				<link href="/logo.ico" rel="icon" />
			</Head>
			<div className="mx-auto max-w-3xl p-5 text-center sm:px-6 lg:px-8">
				{staff ? (
					<div>
						<h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">
							Staff Info
						</h1>
						<div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2">
							<div>
								<Image
									alt={staff.title}
									className="rounded-lg"
									height={200}
									src={staff.img}
									width={200}
								/>
							</div>
							<div className="text-left">
								<h2 className="mt-2 text-2xl font-bold">Staff Name</h2>
								<p className="mt-3 text-xl">{staff.title}</p>
								<h2 className="mt-8 text-2xl font-bold">Education</h2>
								<p className="mt-3 text-xl">Faculty: {staff.faculty}</p>
								<p className="mt-3 text-xl">Major: {staff.major}</p>
								{hasSocialContact && (
									<>
										<h2 className="mt-8 text-2xl font-bold">Social Contact</h2>
										<div className="mt-3">
											{staff.facebook && (
												<Link href={staff.facebook} target="_blank">
													<div
														className="text-blue-500 hover:underline"
														target="_blank"
													>
														Facebook
													</div>
												</Link>
											)}
										</div>
										<div className="mt-3">
											{staff.instagram && (
												<Link href={staff.instagram} target="_blank">
													<div
														className="text-purple-500 hover:underline"
														target="_blank"
													>
														Instagram
													</div>
												</Link>
											)}
										</div>
									</>
								)}
							</div>
						</div>
					</div>
				) : (
					<h4 className="mt-1 text-3xl sm:text-2xl">Staff Not Found</h4>
				)}
			</div>
		</div>
	);
}
